#!/bin/bash

currentColor="ffbb00"
currentDark="222222"
currentWhite="EEEEFF"
currentKeyboard="currentMonitor"
currentMonitor="currentKeyboard"

defaultColor="ffbb00"
defaultMonitor="currentMonitor"
defaultKeyboard="currentKeyboard"