#!/bin/bash

currentColor="ffbb00"
currentDarkLight="222222"
currentKeyboard="currentMonitor"
currentMonitor="currentKeyboard"
currentTheme="Dark" #not yet used

# dont touch default variables
defaultColor="ffbb00"
defaultDark="222222"
defaultWhite="EEEEFF"
defaultMonitor="currentMonitor"
defaultKeyboard="currentKeyboard"
defaultTheme="Dark" #not yet used