#!/bin/bash

# setup background with hyprpaper
mkdir /home/$USER/Documents
mkdir /home/$USER/Downloads
mkdir /home/$USER/Music
mkdir /home/$USER/Music/Playlist
mkdir /home/$USER/Pictures
mkdir /home/$USER/Pictures/Backgrounds
mkdir /home/$USER/Videos