#!/bin/bash

# Function to handle the installation
install_timeshift() {
    echo "------------------------------------------"
    echo "  Starting Timeshift Installation"
    echo "------------------------------------------"

    sudo apt update -y
    sudo apt install -y software-properties-common
    sudo add-apt-repository -y ppa:teejee2008/timeshift
    sudo apt update -y
    sudo apt install -y timeshift

    echo "------------------------------------------"
    echo "  Installation Complete!"
    echo "------------------------------------------"
}

# Logic to check the command line argument
case "$1" in
    installTimeshift)
        install_timeshift
        ;;
    *)
        echo "Usage: $0 {installTimeshift}"
        echo "Example: ./ubuntuTimeshift installTimeshift"
        exit 1
        ;;
esac