#!/bin/bash

#sudo chmod u+x fileName.sh

source /home/$USER/.config/hypr/currentVariables

echo $defaultColor
echo $currentColor
echo $defaultKeyboard
echo $currentKeyboard
echo $defaultMonitor
echo $currentMonitor

var1="$1"
newColor="$2"

updateKeyboard=(
    # /home/$USER/.config/HyprV/current/currentKeyboard
    /home/$USER/.config/HyprV/waybar/conf/waybar_top.jsonc
)

updateMonitor=(
    # /home/$USER/.config/HyprV/current/currentMonitor
    /home/$USER/.config/HyprV/waybar/conf/waybar_top.jsonc
    /home/$USER/.config/HyprV/waybar/conf/waybar_bottom.jsonc
)

updateColors=(
    # /home/$USER/.config/HyprV/current/currentColor
    # gtk (thunar)
    /home/$USER/.config/gtk-3.0/gtk.css
    # wofi
    /home/$USER/.config/wofi/style.css
    /home/$USER/.config/HyprV/wofi/style/wofi_dark.css
    /home/$USER/.config/HyprV/wofi/style/wofi_light.css
    # starship shell
    /home/$USER/.config/HyprV/starship/starship.toml
    # waybar
    /home/$USER/.config/HyprV/waybar/style/waybar_dark.css
    /home/$USER/.config/HyprV/waybar/style/waybar_light.css
    /home/$USER/.config/waybar/buttonApps.py
    /home/$USER/.config/waybar/buttonScripts.py
    /home/$USER/.config/waybar/buttonFiles.py
    /home/$USER/.config/waybar/buttonPower.py
    # wlogout
    /home/$USER/.config/HyprV/wlogout/style/wlogout_dark.css
    /home/$USER/.config/HyprV/wlogout/style/wlogout_light.css
    # mako
    /home/$USER/.config/HyprV/mako/conf/mako_dark
    /home/$USER/.config/HyprV/mako/conf/mako_light
    # firefox
    /home/$USER/.mozilla/firefox/*.default-release/chrome/userChrome.css
    /home/$USER/.mozilla/firefox/*.default-release/chrome/userContent.css
    # librewolf
    /home/$USER/.librewolf/*.default-default/chrome/userChrome.css
    /home/$USER/.librewolf/*.default-default/chrome/userContent.css
    #hyprland (border)
    /home/$USER/.config/HyprV/hypr/hyprland.conf
)

updateDarkLight=(
    /home/$USER/.config/waybar/buttonApps.py
    /home/$USER/.config/waybar/buttonScripts.py
    /home/$USER/.config/waybar/buttonFiles.py
    /home/$USER/.config/waybar/buttonPower.py
)

if [ "$var1" == updateConfigs ]; then

    echo "Updating Configs"

    for CONFIGS in ${updateColors[@]}; do
        sed -i "s/$defaultColor/$currentColor/g" $CONFIGS
    done

    for CONFIGS in ${updateKeyboard[@]}; do
        sed -i "s/$defaultKeyboard/$currentKeyboard/g" $CONFIGS
    done

    for CONFIGS in ${updateMonitor[@]}; do
        sed -i "s/$defaultMonitor/$currentMonitor/g" $CONFIGS
    done

elif [ "$var1" == updateColors ]; then

    echo "Updating colors"
    echo $newColor

    for CONFIGS in ${updateColors[@]}; do
        sed -i "s/$currentColor/$newColor/g" $CONFIGS
    done

elif [ "$var1" == updateDark ]; then

    echo "Updating to dark backgrounds"
    
    for CONFIGS in ${updateDarkLight[@]}; do
        sed -i "s/bg=\"#$defaultLight\"/bg=\"#$defaultDark\"/" $CONFIGS
        sed -i "s/fg=\"#$defaultDark\"/fg=\"#$defaultLight\"/" $CONFIGS
    done

    sed -i "s/currentDarkLight=\"$currentDarkLight\"/currentDarkLight=\"$defaultDark\"/" /home/$USER/.config/hypr/currentVariables

elif [ "$var1" == updateLight ]; then

    echo "Updating to light backgrounds"

    for CONFIGS in ${updateDarkLight[@]}; do
        sed -i "s/bg=\"#$defaultDark\"/bg=\"#$defaultLight\"/" $CONFIGS
        sed -i "s/fg=\"#$defaultLight\"/fg=\"#$defaultDark\"/" $CONFIGS
    done

    sed -i "s/currentDarkLight=\"$currentDarkLight\"/currentDarkLight=\"$defaultLight\"/" /home/$USER/.config/hypr/currentVariables

else
    echo "OK bye"
fi

sleep 1

ln -sf /home/$USER/.config/HyprV/waybar/conf/waybar_top.jsonc /home/$USER/.config/waybar/config.jsonc
ln -sf /home/$USER/.config/HyprV/waybar/style/waybar_dark.css /home/$USER/.config/waybar/style.css
ln -sf /home/$USER/.config/HyprV/kitty/MochaDark.conf /home/$USER/.config/HyprV/kitty/mocha.conf
ln -sf /home/$USER/.config/HyprV/hypr/hyprland.conf /home/$USER/.config/hypr/hyprland.conf

sleep 1

makoctl reload
hyprctl reload