#!/bin/bash

#needs yay mpv-mpris

#get private ip
artist=$(playerctl metadata artist --player=mpv)
title=$(playerctl metadata title --player=mpv)
album=$(playerctl metadata album --player=mpv)
#next=$(playerctl next)



if [ x"${artist}" == "x" ]
then
    artist="$($artist)"
    #echo "Off"
else
    artist="${artist} - "
    #echo "On"
fi

#echo $artist

#TOOLTIP=$album

#echo '{"text": "'$artist' - '$title'", "tooltip": "'$TOOLTIP'"}'
echo '{"text": "'$artist''$title'"}'