#!/bin/bash

if test -e "/home/$USER/.config/waybar/buttonApps.py"; then

    python3 /home/$USER/.config/waybar/buttonApps.py 1>/dev/null &

    sleep .5

    width=$(hyprctl -j clients | jq -r '.[] | select(.title=="Apps") | .size[0]')
    height=$(hyprctl -j clients | jq -r '.[] | select(.title=="Apps") | .size[1]')

    newWidth=$(($width))
    newHeight=$((1080 - $height -55))

    echo $newWidth
    echo $newHeight

    newLine="root.geometry('+50+"$newHeight"')"

    echo $newLine

    # sed -i "11s/.*/$newLine/" /home/$USER/.config/waybar/buttonApps.py
    sed -i "10s/.*/$newLine/" /home/$USER/.config/waybar/buttonApps.py

else
    cp /home/$USER/Hyprland2.0/HyprV/waybar/scripts/buttonApps.py /home/$USER/.config/waybar/buttonApps.py

    python3 /home/$USER/.config/waybar/buttonApps.py 1>/dev/null &
fi