#!/bin/bash

source /home/$USER/.config/hypr/currentVariables

echo "$buttons" # returns on or off

var1="$1"

if [ "$var1" == Apps ]; then

    if test -e "/home/$USER/.config/waybar/buttonApps.py"; then
        
        python3 /home/$USER/.config/waybar/buttonApps.py 1>/dev/null &

        sleep .5

        width=$(hyprctl -j clients | jq -r '.[] | select(.title=="Apps") | .size[0]')
        height=$(hyprctl -j clients | jq -r '.[] | select(.title=="Apps") | .size[1]')

        newWidth=$(($width))
        newHeight=$((1080 - $height -55))
        newLine="root.geometry('+150+"$newHeight"')"

        echo $newLine

        sed -i "11s/.*/$newLine/" /home/$USER/.config/waybar/buttonApps.py

        hyprctl keyword bind , mouse:273, exec, bash "/home/$USER/Hyprland2.0/HyprV/waybar/scripts/buttonsKill" kill
        hyprctl keyword unbind SUPER, SUPER_L
        hyprctl keyword bind SUPER, SUPER_L, exec, bash "/home/$USER/Hyprland2.0/HyprV/waybar/scripts/buttonsKill" kill

    else
        cp /home/$USER/Hyprland2.0/HyprV/waybar/scripts/buttonApps.py /home/$USER/.config/waybar/buttonApps.py

        python3 /home/$USER/.config/waybar/buttonApps.py 1>/dev/null &
    fi

elif [ "$var1" == Scripts ]; then

    if test -e "/home/$USER/.config/waybar/buttonScripts.py"; then

        python3 /home/$USER/.config/waybar/buttonScripts.py 1>/dev/null &

        sleep .5

        width=$(hyprctl -j clients | jq -r '.[] | select(.title=="Scripts") | .size[0]')
        height=$(hyprctl -j clients | jq -r '.[] | select(.title=="Scripts") | .size[1]')

        newWidth=$(($width))
        newHeight=$((1080 - $height -55))
        newLine="root.geometry('+50+"$newHeight"')"

        echo $newLine

        sed -i "11s/.*/$newLine/" /home/$USER/.config/waybar/buttonScripts.py

        hyprctl keyword bind , mouse:273, exec, bash "/home/$USER/Hyprland2.0/HyprV/waybar/scripts/buttonsKill" kill
        hyprctl keyword unbind CONTROL, CONTROL_L
        hyprctl keyword bind CONTROL, CONTROL_L, exec, bash "/home/$USER/Hyprland2.0/HyprV/waybar/scripts/buttonsKill" kill

    else
        cp /home/$USER/Hyprland2.0/HyprV/waybar/scripts/buttonScripts.py /home/$USER/.config/waybar/buttonScripts.py

        python3 /home/$USER/.config/waybar/buttonScripts.py 1>/dev/null &
    fi

elif [ "$var1" == Files ]; then

    if test -e "/home/$USER/.config/waybar/buttonFiles.py"; then

        python3 /home/$USER/.config/waybar/buttonFiles.py 1>/dev/null &

        sleep .5

        width=$(hyprctl -j clients | jq -r '.[] | select(.title=="Files") | .size[0]')
        height=$(hyprctl -j clients | jq -r '.[] | select(.title=="Files") | .size[1]')

        newWidth=$(($width))
        newHeight=$((1080 - $height -55))

        echo $newWidth
        echo $newHeight

        # newLine="root.geometry('+225+"$newHeight"')"
        newLine="root.geometry('+225+${newHeight}')"


        echo $newLine

        # sed -i "11s/.*/$newLine/" /home/$USER/.config/waybar/buttonFiles.py
        sed -i "11s|.*|$newLine|" /home/$USER/.config/waybar/buttonFiles.py

        hyprctl keyword bind , mouse:273, exec, bash "/home/$USER/Hyprland2.0/HyprV/waybar/scripts/buttonsKill" kill
        hyprctl keyword unbind ALT, ALT_L
        hyprctl keyword bind ALT, ALT_L, exec, bash "/home/$USER/Hyprland2.0/HyprV/waybar/scripts/buttonsKill" kill

    else
        cp /home/$USER/Hyprland2.0/HyprV/waybar/scripts/buttonFiles.py /home/$USER/.config/waybar/buttonFiles.py

        python3 /home/$USER/.config/waybar/buttonFiles.py 1>/dev/null &
    fi

elif [ "$var1" == Power ]; then

    if test -e "/home/$USER/.config/waybar/buttonPower.py"; then

        python3 /home/$USER/.config/waybar/buttonPower.py 1>/dev/null &

        sleep .5

        width=$(hyprctl -j clients | jq -r '.[] | select(.title=="Power") | .size[0]')
        height=$(hyprctl -j clients | jq -r '.[] | select(.title=="Power") | .size[1]')

        newWidth=$(($width))
        newHeight=$((50))

        echo $newWidth
        echo $newHeight

        newLine="root.geometry('+10+"$newHeight"')"

        echo $newLine

        sed -i "11s/.*/$newLine/" /home/$USER/.config/waybar/buttonPower.py

        hyprctl keyword bind , mouse:273, exec, bash "/home/$USER/Hyprland2.0/Bash/killDropdowns" kill

    else
        cp /home/$USER/Hyprland2.0/HyprV/waybar/scripts/buttonPower.py /home/$USER/.config/waybar/buttonPower.py

        python3 /home/$USER/.config/waybar/buttonPower.py 1>/dev/null &
    fi
else
    echo "K bye"
fi

#reboot