#!/bin/bash

if test -e "/home/$USER/.config/waybar/buttonPowerButton.py"; then

    python3 /home/$USER/.config/waybar/buttonPowerButton.py 1>/dev/null &

    sleep .5

    width=$(hyprctl -j clients | jq -r '.[] | select(.title=="Apps") | .size[0]')
    height=$(hyprctl -j clients | jq -r '.[] | select(.title=="Apps") | .size[1]')

    newWidth=$(($width))
    newHeight=$((50))

    echo $newWidth
    echo $newHeight

    newLine="root.geometry('+10+"$newHeight"')"

    echo $newLine

    sed -i "10s/.*/$newLine/" /home/$USER/.config/waybar/buttonPowerButton.py

else
    cp /home/$USER/Hyprland2.0/HyprV/waybar/scripts/buttonPowerButton.py /home/$USER/.config/waybar/buttonPowerButton.py

    python3 /home/$USER/.config/waybar/buttonPowerButton.py 1>/dev/null &
fi