#!/bin/bash

if test -e "/home/$USER/.config/waybar/buttonDropDown.py"; then

    python3 /home/$USER/.config/waybar/buttonDropDown.py 1>/dev/null &

    sleep .5

    width=$(hyprctl -j clients | jq -r '.[] | select(.title=="dropDown") | .size[0]')
    height=$(hyprctl -j clients | jq -r '.[] | select(.title=="dropDown") | .size[1]')

    newWidth=$(($width))
    newHeight=$((57))

    echo $newWidth
    echo $newHeight

    newLine="root.geometry('+1080+"$newHeight"')"

    echo $newLine

    sed -i "11s/.*/$newLine/" /home/$USER/.config/waybar/buttonDropDown.py

else
    cp /home/$USER/Hyprland2.0/HyprV/waybar/scripts/buttonDropDown.py /home/$USER/.config/waybar/buttonDropDown.py

    python3 /home/$USER/.config/waybar/buttonDropDown.py 1>/dev/null &
fi