#!/bin/bash

#needs yay mpv-mpris

#get private ip
artist=$(playerctl metadata artist --player=mpv)
title=$(playerctl metadata title --player=mpv)
# album=$(playerctl metadata album --player=mpv)
#next=$(playerctl next)



if [ x"${artist}" == "x" ]
then
    artist="$($artist)"
    #echo "Off"
else
    artist="${artist} - "
    #echo "On"
fi

# artist2=$(tr "&" + <<< "$artist")
artist2=$(sed 's/&/+/g' <<< "$artist")
title2=$(sed 's/&/+/g' <<< "$title")

#echo $artist

#TOOLTIP=$album

#echo '{"text": "'$artist' - '$title'", "tooltip": "'$TOOLTIP'"}'
echo '{"text": "'$artist2''$title2'"}'