#!/bin/bash

MODE=$1

# Convert input to lowercase to be flexible
case "${MODE,,}" in
    integrated)
        echo "Switching to Integrated mode..."
        sudo supergfxctl -m Integrated
        echo "Logging out in 3 seconds..."
        sleep 3
        # Standard command to log out of KDE/GNOME/Hyprland
        loginctl terminate-user $USER
        ;;
        
    hybrid)
        echo "Switching to Hybrid mode..."
        sudo supergfxctl -m Hybrid
        echo "Logging out in 3 seconds..."
        sleep 3
        loginctl terminate-user $USER
        ;;
        
    mux|dedicated|asuxmuxdgpu)
        echo "Switching to MUX (Ultimate) mode..."
        sudo supergfxctl -m AsusMuxDgpu
        echo "REBOOTING in 5 seconds... Save your work!"
        sleep 5
        systemctl reboot
        ;;
        
    *)
        echo "Usage: ./set-gpu [integrated | hybrid | mux]"
        echo "Current Mode: $(supergfxctl -g)"
        ;;
esac