#!/bin/bash
. ~/.config/HyprV/hyprv.conf

get_theme() {
    # Check which waybar theme is set
    #THEMEIS=$(readlink -f ~/.config/waybar/style.css | cut -d '-' -f3) 
    #THEMEIS=$(readlink -f ~/.config/waybar/style.css | cut -d '-' -f3) #Return Dark.css
    THEMEIS=$(readlink -f ~/.config/waybar/style.css | cut -d '/' -f8) #Return Tr3ble-Dark.css

    #if the theme is not dark then we need to switch to it
    if [[ $THEMEIS == "Tr3ble-Dark.css" ]]; then
        SWITCHTO=""
        MODESTR="Light"
    else
        SWITCHTO="-dark"
        MODESTR="Dark"
    fi
}

get_ver() {
    VER=$(readlink -f ~/.config/waybar/config.jsonc | cut -d '-' -f1 | cut -d '/' -f8) #returns Tr3ble
}

restart_waybar() {
    #restart the waybar
    pkill waybar
    waybar & 

    get_ver   

    #if [[ $VER == "v4" ]]; then
    if [[ $VER == "Tr3ble" ]]; then
        #waybar --config ~/.config/HyprV/waybar/conf/v4-config-bottom.jsonc
        waybar --config ~/.config/HyprV/waybar/conf/Tr3ble-Bottom.jsonc
    fi
}

switch_version() {
    get_theme #Return Tr3ble-Dark.css
    get_ver #returns Tr3ble
    case $THEMEIS in
        Tr3ble-Light.css)
            #we are on Tr3ble-Dark so switch to Tr3ble-Dark
            VERTO="Tr3ble-Dark"
            notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "switching to Tr3ble Dark"
            #set the waybar config
            ln -sf ~/.config/HyprV/waybar/conf/Tr3ble-Top.jsonc ~/.config/waybar/config.jsonc
            #set the waybar theme
            ln -sf ~/.config/HyprV/waybar/style/Tr3ble-Dark.css ~/.config/waybar/style.css
            #set the wofi theme
            ln -sf ~/.config/HyprV/wofi/style/Wofi-Tr3ble-Dark.css ~/.config/wofi/style.css           
            #set kitty Theme
            ln -sf ~/.config/HyprV/kitty/MochaDark.conf ~/.config/HyprV/kitty/mocha.conf
            kill -SIGUSR1 $(pidof kitty)
            #set icon themes
            xfconf-query -c xsettings -p /Net/IconThemeName -s "Papirus-Dark"
            gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"
            xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita-dark"
            gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
        ;;

        Tr3ble-Dark.css)
            #we are on Tr3ble-Dark so switch to Tr3ble Light
            VERTO="Tr3ble-Light"
            notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "switching to Tr3ble Light"
            #set the waybar config
            ln -sf ~/.config/HyprV/waybar/conf/Tr3ble-Top.jsonc ~/.config/waybar/config.jsonc
            #set the waybar theme
            ln -sf ~/.config/HyprV/waybar/style/Tr3ble-Light.css ~/.config/waybar/style.css
            #set the wofi theme
            ln -sf ~/.config/HyprV/wofi/style/Wofi-Tr3ble-Light.css ~/.config/wofi/style.css
            #set kitty Theme
            ln -sf ~/.config/HyprV/kitty/MochaLight.conf ~/.config/HyprV/kitty/mocha.conf
            kill -SIGUSR1 $(pidof kitty)
            #set icon themes
            xfconf-query -c xsettings -p /Net/IconThemeName -s "Papirus-Light"
            gsettings set org.gnome.desktop.interface icon-theme "Papirus-Light"
            xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita"
            gsettings set org.gnome.desktop.interface gtk-theme "Adwaita"
        ;;
        
    esac
}

switch_keyboard() {
    hyprctl switchxkblayout $SET_KB next
}

if [[ "$1" == "vswitch" ]]; then
    switch_version
    update_theme
    restart_waybar
elif [[ "$1" == "setbg" ]]; then
    set_current_background
    update_theme
    restart_waybar
elif [[ "$1" == "swkb" ]]; then
    switch_keyboard
    restart_waybar
fi

# need to show the version and tooltip
get_ver

TOOLTIP='Default Keybinds\n'\
'-------------------------------------\n'\
'SUPER + # = Change Workspace\n'\
'SUPER + ALT + # = Move to Workspace\n'\
'ALT + # = Change/Move to Workspace\n'\
'-------------------------------------\n'\
'ALT + A = Audacity\n'\
'ALT + B = Blender\n'\
'ALT + C = Calculator (galculator)\n'\
'ALT + D = Discord (webcord)\n'\
'ALT + E = File Manager (Thunar)\n'\
'ALT + F = Firefox\n'\
'ALT + G = Gimp\n'\
'ALT + M = Mail/Calendar (Evolution)\n'\
'ALT + N = Notes (Zim)\n'\
'ALT + Q = Close Window\n'\
'ALT + S = Steam\n'\
'ALT + T = Terminal (Kitty)\n'\
'ALT + V = VSCode\n'\
'ALT + W = Background (waypaper)\n'\
'-------------------------------------\n'\
'SUPER + C = Open clipboard manager\n'\
'SUPER + L = Lock Screen\n'\
'SUPER + M = Logout menu\n'\
'SUPER + S = Screenshot\n'\
'SUPER + V = Toggle Float\n'\
'SUPER + SPACE = App Launcher'\

echo '{"text": "'$VER'", "tooltip": "'$TOOLTIP'"}'
#echo '{"text": "Tr3ble", "tooltip": "'$TOOLTIP'"}'