#!/bin/bash

#Set your keyboard name here and in waybar waybar_top.jsonc 
#hyprctl devices
SET_KB="keyboard-k380-keyboard"

get_theme() {
    # Check which waybar theme is set
    THEMEIS=$(readlink -f ~/.config/waybar/style.css | cut -d '/' -f8) #Return waybar_dark.css

    #if the theme is not dark then we need to switch to it
    if [[ $THEMEIS == "waybar_dark.css" ]]; then
        # SWITCHTO=""
        MODESTR="light"
    else
        # SWITCHTO="_dark"
        MODESTR="dark"
    fi
}

get_ver() {
    VER=$(readlink -f ~/.config/waybar/config.jsonc | cut -d '_' -f1 | cut -d '/' -f8) #returns waybar
}

restart_waybar() {
    #restart the waybar
    pkill waybar
    waybar & 

    get_ver   

    #if [[ $VER == "v4" ]]; then
    if [[ $VER == "waybar" ]]; then
        waybar --config ~/.config/HyprV/waybar/conf/waybar_bottom.jsonc
    fi
}

switch_version() {
    get_theme #Return waybar_dark.css
    get_ver #returns waybar
    case $THEMEIS in
        waybar_light.css)
            #we are on waybar_light so switch to waybar_dark
            VERTO="waybar_dark"
            notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "Switching to Dark Theme"
            #set waybar theme
            ln -sf ~/.config/HyprV/waybar/conf/waybar_top.jsonc ~/.config/waybar/config.jsonc
            #set waybar theme
            ln -sf ~/.config/HyprV/waybar/style/waybar_dark.css ~/.config/waybar/style.css
            #set wofi theme
            ln -sf ~/.config/HyprV/wofi/style/wofi_dark.css ~/.config/wofi/style.css
            #set wlogout theme
            ln -sf ~/.config/HyprV/wlogout/style/wlogout_dark.css ~/.config/wlogout/style.css
            #set starship shell theme
            ln -sf ~/.config/HyprV/starship/starship.toml ~/.config/starship.toml
            #set mako theme
            ln -sf ~/.config/HyprV/mako/conf/mako_dark ~/.config/mako/config
            makoctl reload
            #set kitty Theme
            ln -sf ~/.config/HyprV/kitty/kitty_dark.conf ~/.config/kitty/kitty.conf
            kill -SIGUSR1 $(pidof kitty)

            #set background
            #swww img ~/.config/HyprV/backgrounds/background_dark.jpg --transition-fps 60 --transition-type wipe --transition-duration 2
            #set sddm image
            # cp -f ~/.config/HyprV/backgrounds/background_dark.jpg /usr/share/sddm/themes/sdt/wallpaper.jpg
            
            #set icon themes
            xfconf-query -c xsettings -p /Net/IconThemeName -s "Papirus-Dark"
            gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"
            xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita-dark"
            gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
        ;;

        waybar_dark.css)
            #we are on waybar_dark so switch to waybar_light
            VERTO="waybar_light"
            notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "Switching to Light Theme"
            #set waybar theme
            ln -sf ~/.config/HyprV/waybar/conf/waybar_top.jsonc ~/.config/waybar/config.jsonc
            #set waybar theme
            ln -sf ~/.config/HyprV/waybar/style/waybar_light.css ~/.config/waybar/style.css
            #set wofi theme
            ln -sf ~/.config/HyprV/wofi/style/wofi_light.css ~/.config/wofi/style.css
            #set wlogout theme
            ln -sf ~/.config/HyprV/wlogout/style/wlogout_light.css ~/.config/wlogout/style.css
            #set starship shell theme
            ln -sf ~/.config/HyprV/starship/starship.toml ~/.config/starship.toml
            #set mako theme
            ln -sf ~/.config/HyprV/mako/conf/mako_light ~/.config/mako/config
            makoctl reload
            #set kitty Theme
            ln -sf ~/.config/HyprV/kitty/kitty_light.conf ~/.config/kitty/kitty.conf
            kill -SIGUSR1 $(pidof kitty)

            #set background
            #swww img ~/.config/HyprV/backgrounds/background_light.jpg --transition-fps 60 --transition-type wipe --transition-duration 2
            #set sddm image
            # cp -f ~/.config/HyprV/backgrounds/background_light.jpg /usr/share/sddm/themes/sdt/wallpaper.jpg

            #set icon themes
            xfconf-query -c xsettings -p /Net/IconThemeName -s "Papirus-Light"
            gsettings set org.gnome.desktop.interface icon-theme "Papirus-Light"
            xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita"
            gsettings set org.gnome.desktop.interface gtk-theme "Adwaita"
        ;;
        
    esac
}

switch_keyboard() {
    hyprctl switchxkblayout $SET_KB next
}

if [[ "$1" == "vswitch" ]]; then
    switch_version
    update_theme
    restart_waybar
elif [[ "$1" == "setbg" ]]; then
    set_current_background
    update_theme
    restart_waybar
elif [[ "$1" == "swkb" ]]; then
    switch_keyboard
    restart_waybar
fi

# need to show the version and tooltip
get_ver

TOOLTIP='------------------\n'\
'Move Things Around\n'\
'------------------\n'\
'SUPER + # = Change Workspace\n'\
'SUPER + ALT + # = Move to Workspace\n'\
'ALT + # = Change/Move to Workspace\n'\
'ALT + TAB = Toggle Waybar\n'\
'-------------------\n'\
'Open and Close Apps\n'\
'-------------------\n'\
'ALT + A = Audacity\n'\
'ALT + B = Blender\n'\
'ALT + C = Calculator (galculator)\n'\
'ALT + D = Discord (webcord)\n'\
'ALT + E = File Manager (Thunar)\n'\
'ALT + F = Firefox\n'\
'ALT + G = Gimp\n'\
'ALT + M = Mail/Calendar (Evolution)\n'\
'ALT + N = Notes (Zim)\n'\
'ALT + Q = Close Window\n'\
'ALT + S = Steam\n'\
'ALT + T = Terminal (Kitty)\n'\
'ALT + V = VSCode\n'\
'ALT + W = Background (waypaper)\n'\
'----------\n'\
'Main Tools\n'\
'----------\n'\
'SUPER + C = Open clipboard manager\n'\
'SUPER + L = Lock Screen\n'\
'SUPER + M = Logout menu\n'\
'SUPER + Q = Screenshot\n'\
'SUPER + T = Light/Dark Mode\n'\
'SUPER + V = Toggle Float\n'\
'SUPER + SPACE = App Launcher\n'\
'ALT + L = Toggle Hidden Workspace (Playlist)\n'\
'ALT + K = Move to Hidden Workspace (Playlist)\n'\
'--------\n'\
'Playlist\n'\
'--------\n'\
'ALT + P = Play Playlist\n'\
'ALT + [ = Play Previous Song\n'\
'ALT + ] = Play Next Song\n'\
'ALT + \\ = Stop Playlist'\

# echo '{"text": "'$VER'", "tooltip": "'$TOOLTIP'"}'
echo '{"text": "Tr3ble", "tooltip": "'$TOOLTIP'"}'