#!/bin/bash

#token=57f92d8d69a152
token=8b928b8ffd980d

#get private ip
privateIP=$(curl ifconfig.co)

#get geo location from private ip
url=$(curl ipinfo.io/$privateIP?token=$token)
#store info in newUrl variable
newUrl=$url

#cut newUrl into list (cut -d',' -f1 <<< "$newUrl")
#select line (sed -n '/"city"/p')
#trim bigining (sed 's/^.\{11\}//')
#trim end (sed 's/.\{1\}$//')
city=$(cut -d',' -f1 <<< "$newUrl" | sed -n '/"city"/p' | sed 's/^.\{11\}//' | sed 's/.\{1\}$//')
region=$(cut -d',' -f1 <<< "$newUrl" | sed -n '/"region"/p' | sed 's/^.\{13\}//' | sed 's/.\{1\}$//')
country=$(cut -d',' -f1 <<< "$newUrl" | sed -n '/"country"/p' | sed 's/^.\{14\}//' | sed 's/.\{1\}$//')

#get local IP information
connectionName=$(nmcli device show | grep -o 'GENERAL.DEVICE.*' | cut -d: -f2 | awk '{print $1}' | head -1)
connectionIP=$(nmcli device show | grep -o 'IP4.ADDRESS.*' | cut -d: -f2 | awk '{print $1}' | head -1)

#to show all markets
#curl terminal-stocks.dev/market-summary
spyPrice=$(curl terminal-stocks.dev/market-summary | sed -n '5p' | awk '{print $5}' | sed 's/^.\{5\}//' | sed 's/.\{5\}$//')
spyPercent=$(curl terminal-stocks.dev/market-summary | sed -n '5p' | awk '{print $9}' | sed 's/^.\{5\}//' | sed 's/.\{5\}$//')
dowPrice=$(curl terminal-stocks.dev/market-summary | sed -n '7p' | awk '{print $7}' | sed 's/^.\{5\}//' | sed 's/.\{5\}$//')
dowPercent=$(curl terminal-stocks.dev/market-summary | sed -n '7p' | awk '{print $11}' | sed 's/^.\{5\}//' | sed 's/.\{5\}$//')
nasdaqPrice=$(curl terminal-stocks.dev/market-summary | sed -n '9p' | awk '{print $5}' | sed 's/^.\{5\}//' | sed 's/.\{5\}$//')
nasdaqPercent=$(curl terminal-stocks.dev/market-summary | sed -n '9p' | awk '{print $9}' | sed 's/^.\{5\}//' | sed 's/.\{5\}$//')
tsxPrice=$(curl terminal-stocks.dev/^gsptse | sed -n '5p' | awk '{print $6}' | sed 's/^.\{5\}//' | sed 's/.\{5\}$//')
tsxPercent=$(curl terminal-stocks.dev/^gsptse | sed -n '5p' | awk '{print $10}' | sed 's/^.\{5\}//' | sed 's/.\{5\}$//')

TOOLTIP='Network:\n'\
'Public IP = '$privateIP'\n'\
$city', '$region', '$country'\n'\
'Private IP = '$connectionName' ('$connectionIP')\n\n'\
'Markets:\n'\
'SPY = '$spyPrice' ('$spyPercent')\n'\
'DOW = '$dowPrice' ('$dowPercent')\n'\
'NASDAQ = '$nasdaqPrice' ('$nasdaqPercent')\n'\
'TSX = '$tsxPrice' ('$tsxPercent'%)'\

#echo '{"text": "'Info'", "tooltip": "'$TOOLTIP'"}'
echo '{"text": "'$city', '$region', '$country'", "tooltip": "'$TOOLTIP'"}'