#!/bin/bash

#see dispatcher
#https://wiki.hyprland.org/Configuring/Dispatchers/


floatValue=$(hyprctl activewindow -j)

floatValue2=$(cut -d',' -f1 <<< "$floatValue" | sed -n '/"floating"/p' | sed 's/^.\{15\}//')

if $floatValue2; then
    hyprctl dispatch togglefloating
    hyprctl setprop active opaque toggle
else
    hyprctl dispatch togglefloating
    hyprctl dispatch resizeactive exact 480 270
    # hyprctl dispatch moveactive exact 1435 5
    hyprctl dispatch moveactive exact 3355 5
    hyprctl dispatch pin
    hyprctl setprop active opaque toggle
    # hyprctl dispatch centerwindow
fi