#!/bin/bash

sudo su <<HERE
rm -r /home/$USER/Hyprland2.0
HERE

notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "Updating config files"

git clone https://github.com/GuillaumeGodin/Hyprland2.0

currentColor=$(cat /home/$USER/.config/HyprV/currentColor)
defaultColor=$(cat /home/$USER/Hyprland2.0/Bash/Color/currentColor)

# echo $defaultColor
# echo $currentColor

sleep 3

rm -r /home/$USER/.config/HyprV
cp -r /home/$USER/Hyprland2.0/HyprV /home/$USER/.config/HyprV

#hyprland (border)
sed -i "s/$defaultColor/$currentColor/g" ~/.config/HyprV/hypr/hyprland.conf
# gtk (thunar)
sed -i "s/$defaultColor/$currentColor/g" ~/.config/gtk-3.0/gtk.css
# wofi
sed -i "s/$defaultColor/$currentColor/g" ~/.config/wofi/style.css
sed -i "s/$defaultColor/$currentColor/g" ~/.config/HyprV/wofi/style/wofi_dark.css
sed -i "s/$defaultColor/$currentColor/g" ~/.config/HyprV/wofi/style/wofi_light.css
# starship shell
sed -i "s/$defaultColor/$currentColor/g" ~/.config/HyprV/starship/starship.toml
# waybar
sed -i "s/$defaultColor/$currentColor/g" ~/.config/HyprV/waybar/style/waybar_dark.css
sed -i "s/$defaultColor/$currentColor/g" ~/.config/HyprV/waybar/style/waybar_light.css
# wlogout
sed -i "s/$defaultColor/$currentColor/g" ~/.config/HyprV/wlogout/style/wlogout_dark.css
sed -i "s/$defaultColor/$currentColor/g" ~/.config/HyprV/wlogout/style/wlogout_light.css
# mako
sed -i "s/$defaultColor/$currentColor/g" ~/.config/HyprV/mako/conf/mako_dark
sed -i "s/$defaultColor/$currentColor/g" ~/.config/HyprV/mako/conf/mako_light
# firefox
sed -i "s/$defaultColor/$currentColor/g" ~/.mozilla/firefox/*.default-release/chrome/userChrome.css
sed -i "s/$defaultColor/$currentColor/g" ~/.mozilla/firefox/*.default-release/chrome/userContent.css
# librewolf
sed -i "s/$defaultColor/$currentColor/g" ~/.librewolf/*.default-default/chrome/userChrome.css
sed -i "s/$defaultColor/$currentColor/g" ~/.librewolf/*.default-default/chrome/userContent.css
# currentColor
sed -i "s/$defaultColor/$currentColor/g" ~/.config/HyprV/currentColor

ln -sf ~/.config/HyprV/waybar/conf/waybar_top.jsonc ~/.config/waybar/config.jsonc
ln -sf ~/.config/HyprV/waybar/style/waybar_dark.css ~/.config/waybar/style.css
ln -sf ~/.config/HyprV/kitty/MochaDark.conf ~/.config/HyprV/kitty/mocha.conf
ln -sf ~/.config/HyprV/hypr/hyprland.conf ~/.config/hypr/hyprland.conf

makoctl reload
hyprctl reload

# echo $defaultColor
# echo $currentColor


