#!/bin/bash

sudo su <<HERE
rm -r /home/$USER/Hyprland2.0
HERE

notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "Updating config files"

git clone https://github.com/GuillaumeGodin/Hyprland2.0

currentColor=$(cat /home/$USER/.config/HyprV/current/currentColor)
currentMonitor=$(cat /home/$USER/.config/HyprV/current/currentMonitor)
currentKeyboard=$(cat /home/$USER/.config/HyprV/current/currentKeyboard)

defaultColor=$(cat /home/$USER/Hyprland2.0/HyprV/current/currentColor)
defaultMonitor=$(cat /home/$USER/Hyprland2.0/HyprV/current/currentMonitor)
defaultKeyboard=$(cat /home/$USER/Hyprland2.0/HyprV/current/currentKeyboard)

# echo $defaultColor
# echo $currentColor

sleep 1

rm -r /home/$USER/.config/HyprV
cp -r /home/$USER/Hyprland2.0/HyprV /home/$USER/.config/HyprV

# gtk (thunar)
sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/gtk-3.0/gtk.css
# wofi
sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/wofi/style.css
sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/wofi/style/wofi_dark.css
sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/wofi/style/wofi_light.css
# starship shell
sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/starship/starship.toml
# waybar
sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/waybar/style/waybar_dark.css
sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/waybar/style/waybar_light.css
sed -i "s/$defaultMonitor/$currentMonitor/g" /home/$USER/.config/HyprV/waybar/conf/waybar_top.jsonc
sed -i "s/$defaultMonitor/$currentMonitor/g" /home/$USER/.config/HyprV/waybar/conf/waybar_bottom.jsonc
# wlogout
sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/wlogout/style/wlogout_dark.css
sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/wlogout/style/wlogout_light.css
# mako
sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/mako/conf/mako_dark
sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/mako/conf/mako_light
# firefox
sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.mozilla/firefox/*.default-release/chrome/userChrome.css
sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.mozilla/firefox/*.default-release/chrome/userContent.css
# librewolf
sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.librewolf/*.default-default/chrome/userChrome.css
sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.librewolf/*.default-default/chrome/userContent.css
# current
sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/current/currentColor
sed -i "s/$defaultMonitor/$currentMonitor/g" /home/$USER/.config/HyprV/current/currentMonitor
sed -i "s/$defaultKeyboard/$currentKeyboard/g" /home/$USER/.config/HyprV/current/currentKeyboard
# keyboard
sed -i "s/$defaultKeyboard/$currentKeyboard/g" /home/$USER/.config/HyprV/waybar/conf/waybar_top.jsonc
sed -i "s/$defaultKeyboard/$currentKeyboard/g" /home/$USER/.config/HyprV/hyprv_util
#hyprland (border)
sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/hypr/hyprland.conf

sleep 1

ln -sf /home/$USER/.config/HyprV/waybar/conf/waybar_top.jsonc /home/$USER/.config/waybar/config.jsonc
ln -sf /home/$USER/.config/HyprV/waybar/style/waybar_dark.css /home/$USER/.config/waybar/style.css
ln -sf /home/$USER/.config/HyprV/kitty/MochaDark.conf /home/$USER/.config/HyprV/kitty/mocha.conf
ln -sf /home/$USER/.config/HyprV/hypr/hyprland.conf /home/$USER/.config/hypr/hyprland.conf

sleep 1

makoctl reload
hyprctl reload

# echo $defaultColor
# echo $currentColor


