#!/bin/bash

active_window_class=$(hyprctl activewindow -j | jq -r ".class")

if [ "$active_window_class" = "Tk" ]; then
    # hyprctl dispatch killactive
    hyprctl keyword unbind , mouse:273
    hyprctl keyword unbind , escape
    hyprctl keyword unbind CONTROL, CONTROL_L
    hyprctl keyword bindr CONTROL, CONTROL_L, exec, python3 .config/waybar/buttonScripts.py
    hyprctl keyword unbind SUPER, SUPER_L
    hyprctl keyword bindr SUPER, SUPER_L, exec, python3 .config/waybar/buttonApps.py
    hyprctl keyword unbind ALT, ALT_L
    hyprctl keyword bindr ALT, ALT_L, exec, python3 .config/waybar/buttonFiles.py
else
    hyprctl keyword unbind , mouse:273
    hyprctl keyword unbind , escape
    hyprctl keyword unbind CONTROL, CONTROL_L
    hyprctl keyword bindr CONTROL, CONTROL_L, exec, python3 .config/waybar/buttonScripts.py
    hyprctl keyword unbind SUPER, SUPER_L
    hyprctl keyword bindr SUPER, SUPER_L, exec, python3 .config/waybar/buttonApps.py
    hyprctl keyword unbind ALT, ALT_L
    hyprctl keyword bindr ALT, ALT_L, exec, python3 .config/waybar/buttonFiles.py
fi

hyprctl dispatch killwindow class:Tk

# hyprctl cursorpos