#!/bin/bash

#sudo chmod u+x fileName.sh

#From /usr/share/applications/
#To /usr/share/LSP/

mkdir /usr/share/LSP

moveApps=$(ls /usr/share/applications/in.lsp*)

echo $moveApps

for APPS in ${moveApps[@]}; do
    mv $APPS /usr/share/LSP
done