#!/bin/bash

waypaperBackground=$(sed -n 4p /home/$USER/.config/waypaper/config.ini | sed 's/^.\{13\}//')

#variable not used
#waypaperBackground2='/home/$USER'$waypaperBackground

sddmLink=/usr/share/sddm/themes/sdt/wallpaper.jpg

#"" are needed for space (had to keep $USER out thought)
cp /home/$USER"$waypaperBackground" $sddmLink

#echo $waypaperBackground2
#echo $sddmLink