#!/bin/bash

# setup background with hyprpaper

cp /home/$USER/Hyprland2.0/HyprV/backgrounds/Tr3ble-Dark-Background.jpg /home/$USER/Pictures/bg.jpg

sed -i 's/splash = true/#splash = true/g' /home/$USER/.config/hypr/hyprpaper.conf
sed -i 's/exec-once = swww init/exec = hyprpaper/g' /home/$USER/.config/hypr/hyprland.conf