#!/bin/bash
#sudo chmod u+x fileName.sh

#use hyprland git instead of hyprland
yay -S --asdeps hyprutils-git hyprlang-git hyprcursor-git hyprwayland-scanner-git

#the aur/ flag tells yay to use the aur mirror instead of chaotic-aur)
yay -Sy aur/hyprland-git

#sudo su <<HERE
#HERE

#reboot