#!/bin/bash

notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "Switching to Dark Theme"
#set waybar theme
ln -sf ~/.config/HyprV/waybar/conf/waybar_top.jsonc ~/.config/waybar/config.jsonc
#set waybar theme
ln -sf ~/.config/HyprV/waybar/style/waybar_dark.css ~/.config/waybar/style.css
#set wofi theme
ln -sf ~/.config/HyprV/wofi/style/wofi_dark.css ~/.config/wofi/style.css
#set wlogout theme
ln -sf ~/.config/HyprV/wlogout/style/wlogout_dark.css ~/.config/wlogout/style.css
#set starship shell theme
ln -sf ~/.config/HyprV/starship/starship.toml ~/.config/starship.toml
#set mako theme
ln -sf ~/.config/HyprV/mako/conf/mako_dark ~/.config/mako/config
#set kitty Theme
ln -sf ~/.config/HyprV/kitty/kitty_dark.conf ~/.config/kitty/kitty.conf
kill -SIGUSR1 $(pidof kitty)
#set icon themes
xfconf-query -c xsettings -p /Net/IconThemeName -s "Papirus-Dark"
gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"
xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita-dark"
gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"

# reload configs
bash /home/$USER/Hyprland2.0/Scripts/Bash/archReload

# waybar --config ~/.config/HyprV/waybar/conf/waybar_bottom.jsonc